[project]
name = "watchy-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icalendar>=6.1.1",
    "pytz>=2025.1",
    "recurring-ical-events>=3.6.0",
    "requests>=2.32.3",
]
